### ISSUE TITLE
oauth2: multiple redirect urls per client

### ISSUE THREAD

**Issue by mgenov** [clouway/oauth2-server#23]
Support for multiple redirect urls need to be added to provide a way to specify multiple endpoints for a single client.

This configuration will be mostly used for development environment where such configuration is necessary.

cc @mlesikov  @georgievJon

**Comment by mlesikov** [comment]
hm, are you sure that we should do it here? Maybe we should register different clients, and we can setup different id and secrets.

**Comment by mlesikov** [comment]
why do you think here will be better solution, also what is your idea, what are we gonna pass in addition including the app client id

**Comment by mgenov** [comment]
Yes, I'm sure. 

Take a look at callback property at: https://auth0.com/docs/api/management/v2#!/Clients/get_clients

**Comment by mlesikov** [comment]
the property is an array, 

``` json
 "callbacks": [
      "http://localhost/callback"
    ],
```
