### ISSUE TITLE
oauth2: id_token is not a json formatted one

### ISSUE THREAD

**Issue by mgenov** [clouway/oauth2-server#46]
The generated id_token doesn't contain JSON value as ClaimSet is returning toString() representation of the object and not a json object.

**Comment by VasilMitovClouway** [comment]
Was wondering about this issue - now that we have Jjwt library, we could just remove the existing id token builder and just use the librarys DefaultJwtBuilder.Tho this will make RsaJwsSigner( to be implemented in #51 ) obsolete. The other way is to just add toString() methods and properly construct fields to make a JSON.

**Comment by mgenov** [comment]
Yes, jjwt need to be used for signing and generation of jwts.

**Comment by mgenov** [comment]
Should be fixed with #52

**Comment by VasilMitovClouway** [comment]
Fixed in  #52
