### ISSUE TITLE
oauth2: proof key for code exchange

### ISSUE THREAD

**Issue by mgenov** [clouway/oauth2-server#66]
Native apps are vulnerable to attacks caused by interception of authorization code. They may hook up the authorization code and to exchange it for access token which to grant an access to user resources. 

The protection mechanism is described at: 
https://tools.ietf.org/html/rfc7636

**Comment by mgenov** [comment]
https://medium.com/@ageitgey/everything-you-need-to-know-about-implementing-ios-and-android-mobile-deep-linking-f4348b265b49

Implementing Android App Links with Verification section shows an example for verification mechanism which could be used.

**Comment by VasilMitovClouway** [comment]
A quick question: should we keep a backwards compatibility for a normal OAuth2 protocol without this extension ?

**Comment by VasilMitovClouway** [comment]
For instance if the authorization request does not contain a code_verifyer a normal flow is done

**Comment by mgenov** [comment]
Yes, normal flow should be executed if code_verifier is not passed by the client apps. 

oauth2-server should stick to standard oauth2 spec  but should support and additional security extensions which are defined latter.

**Comment by VasilMitovClouway** [comment]
Another question: Will we encounter a problem using Sha 256 algorithm for the flow? Is there anything i should consider? I am thinking of using the "s256" method instead of the "plain"  ofc.

**Comment by mgenov** [comment]
It would be better both to be supported. 

s256 is better option as start
