### ISSUE TITLE
example app: auth endpoint called even if the login has failed

### ISSUE THREAD

**Issue by nagylzs** [clouway/oauth2-server#84]
If you try to start an authorization request in the example app and write in a wrong password, then the following happens:

- the LoginEndpoint will redirect to the continue URL (even though the user could not login)
- then the continue url (the auth endpoint) will redirect to the login endpoint again

The biggest "problem" is that the user will not see an error message.

I have a very small modification to the example app that fixes this problem. Can I send a PR?

**Comment by VasilMitovClouway** [comment]
Of course, we would be glad to see the modification.

**Comment by nagylzs** [comment]
Submitted a PR but the tests are failing. I have never used JMock so I'm not sure how to change the tests but I'll try.

**Comment by mgenov** [comment]
You can remove the whole test as it's an example app and it's purpose is to show example usage.

**Comment by nagylzs** [comment]
I feel I totally messed up the PR. I'm sorry I'm new to this. Maybe I should delete this PR and create a new one.

**Comment by VasilMitovClouway** [comment]
No, don't worry.  No one is born taught.

**Comment by mgenov** [comment]
Fixed with #86
