### ISSUE TITLE
oauth2-server: revoke refresh tokens is not allowed

### ISSUE THREAD

**Issue by qnislavnachev** [clouway/oauth2-server#89]
OAuth2 server does not allow revoking of refresh tokens. As I can see in this topic: https://tools.ietf.org/html/rfc7009#section-2.1 revoking of refresh tokens should be allowed. 

Now when revoke token and we pass refresh token it respond with: 
``` OAuthError.invalidRequest("Token was not found.") ``` ,

because before revoking, it check if the token exists.
``` Optional<BearerToken> possibleToken = tokens.findTokenAvailableAt(token, instant); ```,

but that check looking for access token only and it fails. My opinion is that this check is unnecessary, when the method ``` tokens.revokeToken(token) ``` can do the job.

**Comment by qnislavnachev** [comment]
@mgenov What do you think ?

**Comment by mgenov** [comment]
I think that it's role of the Tokens implementation to lookup for both and not of the library.

**Comment by qnislavnachev** [comment]
That way ``` Optional<BearerToken> possibleToken = tokens.findTokenAvailableAt(token, instant); ```
this interface method should be changed to return ``` TokenResponse ``` or ``` String ``` value ``` maybe.

**Comment by qnislavnachev** [comment]
The issue is outdated.
